enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
build-mode = "module"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"
build-mode = "module"

[Duolingo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo/"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "module"

[Facebook]
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
arch = "arm64-v8a"
build-mode = "module"

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"
build-mode = "module"

[Instagram]
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
arch = "arm64-v8a"
build-mode = "module"

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "module"

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "module"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
included-patches = "'SIM spoof'"
arch = "arm64-v8a"
build-mode = "module"

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
arch = "arm64-v8a"
build-mode = "module"
